// config.js — Plessen Encrypted System Configuration
// Generated by /config-tool — do not edit manually.
// This is an AES-256-GCM encrypted blob. The decryption key lives in
// plessen-auth Firestore (system/keyFragment) and is only accessible
// to authenticated users. Without the key this file is unreadable.
//
// To update: open /config-tool, sign in as superuser, make changes,
// click Generate, download the new config.js and push to GitHub.
const PLESSEN_ENCRYPTED_CONFIG = "PLACEHOLDER_RUN_CONFIG_TOOL";
